
package services.employee;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeePort", targetNamespace = "http://employee.services")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeePort {


    /**
     * 
     * @param callOutputEmployeeRequest
     * @return
     *     returns services.employee.CallOutputEmployeeResponse
     */
    @WebMethod
    @WebResult(name = "callOutputEmployeeResponse", targetNamespace = "http://employee.services", partName = "callOutputEmployeeResponse")
    public CallOutputEmployeeResponse callOutputEmployee(
        @WebParam(name = "callOutputEmployeeRequest", targetNamespace = "http://employee.services", partName = "callOutputEmployeeRequest")
        CallOutputEmployeeRequest callOutputEmployeeRequest);

    /**
     * 
     * @param callFilterEmployeeRequest
     * @return
     *     returns services.employee.CallFilterEmployeeResponse
     */
    @WebMethod
    @WebResult(name = "callFilterEmployeeResponse", targetNamespace = "http://employee.services", partName = "callFilterEmployeeResponse")
    public CallFilterEmployeeResponse callFilterEmployee(
        @WebParam(name = "callFilterEmployeeRequest", targetNamespace = "http://employee.services", partName = "callFilterEmployeeRequest")
        CallFilterEmployeeRequest callFilterEmployeeRequest);

    /**
     * 
     * @param callInsertEmployeeDetailsRequest
     * @return
     *     returns services.employee.CallInsertEmployeeDetailsResponse
     */
    @WebMethod
    @WebResult(name = "callInsertEmployeeDetailsResponse", targetNamespace = "http://employee.services", partName = "callInsertEmployeeDetailsResponse")
    public CallInsertEmployeeDetailsResponse callInsertEmployeeDetails(
        @WebParam(name = "callInsertEmployeeDetailsRequest", targetNamespace = "http://employee.services", partName = "callInsertEmployeeDetailsRequest")
        CallInsertEmployeeDetailsRequest callInsertEmployeeDetailsRequest);

    /**
     * 
     * @param callInsertEmployeeAddressRequest
     * @return
     *     returns services.employee.CallInsertEmployeeAddressResponse
     */
    @WebMethod
    @WebResult(name = "callInsertEmployeeAddressResponse", targetNamespace = "http://employee.services", partName = "callInsertEmployeeAddressResponse")
    public CallInsertEmployeeAddressResponse callInsertEmployeeAddress(
        @WebParam(name = "callInsertEmployeeAddressRequest", targetNamespace = "http://employee.services", partName = "callInsertEmployeeAddressRequest")
        CallInsertEmployeeAddressRequest callInsertEmployeeAddressRequest);

}
