
package web;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TransactionsSoap", targetNamespace = "http://web/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TransactionsSoap {


    /**
     * 
     * @param stringUser
     * @param stringType
     * @return
     *     returns web.GroupOfTransactions
     */
    @WebMethod
    @WebResult(name = "GroupOfTransactions", partName = "GroupOfTransactions")
    @Action(input = "http://web/TransactionsSoap/readAllRequest", output = "http://web/TransactionsSoap/readAllResponse")
    public GroupOfTransactions readAll(
        @WebParam(name = "StringUser", partName = "StringUser")
        String stringUser,
        @WebParam(name = "stringType", partName = "stringType")
        String stringType);

    /**
     * 
     * @param string
     * @return
     *     returns web.GroupOfTransactions
     */
    @WebMethod
    @WebResult(name = "GroupOfTransactions", partName = "GroupOfTransactions")
    @Action(input = "http://web/TransactionsSoap/readAllByUserRequest", output = "http://web/TransactionsSoap/readAllByUserResponse")
    public GroupOfTransactions readAllByUser(
        @WebParam(name = "String", partName = "String")
        String string);

    /**
     * 
     * @param stringUser
     * @param stringStartDate
     * @param stringEndDate
     * @return
     *     returns web.GroupOfTransactions
     */
    @WebMethod
    @WebResult(name = "GroupOfTransactions", partName = "GroupOfTransactions")
    @Action(input = "http://web/TransactionsSoap/readAllDateByUserRequest", output = "http://web/TransactionsSoap/readAllDateByUserResponse")
    public GroupOfTransactions readAllDateByUser(
        @WebParam(name = "StringUser", partName = "StringUser")
        String stringUser,
        @WebParam(name = "stringStartDate", partName = "stringStartDate")
        String stringStartDate,
        @WebParam(name = "stringEndDate", partName = "stringEndDate")
        String stringEndDate);

    /**
     * 
     * @param createAccount
     */
    @WebMethod
    @Action(input = "http://web/TransactionsSoap/createAccountRequest", output = "http://web/TransactionsSoap/createAccountResponse")
    public void createAccount(
        @WebParam(name = "CreateAccount", partName = "CreateAccount")
        Account createAccount);

    /**
     * 
     * @param stringUser
     * @param stringPassword
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "GroupOfTransactions", partName = "GroupOfTransactions")
    @Action(input = "http://web/TransactionsSoap/loginRequest", output = "http://web/TransactionsSoap/loginResponse")
    public boolean login(
        @WebParam(name = "StringUser", partName = "StringUser")
        String stringUser,
        @WebParam(name = "stringPassword", partName = "stringPassword")
        String stringPassword);

}
