
package app.employee.webservice.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EmployeeProfileEndpointService", targetNamespace = "http://endpoint.webservice.employee.app/", wsdlLocation = "http://localhost:8084/employeeform?wsdl")
public class EmployeeProfileEndpointService
    extends Service
{

    private final static URL EMPLOYEEPROFILEENDPOINTSERVICE_WSDL_LOCATION;
    private final static WebServiceException EMPLOYEEPROFILEENDPOINTSERVICE_EXCEPTION;
    private final static QName EMPLOYEEPROFILEENDPOINTSERVICE_QNAME = new QName("http://endpoint.webservice.employee.app/", "EmployeeProfileEndpointService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8084/employeeform?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPLOYEEPROFILEENDPOINTSERVICE_WSDL_LOCATION = url;
        EMPLOYEEPROFILEENDPOINTSERVICE_EXCEPTION = e;
    }

    public EmployeeProfileEndpointService() {
        super(__getWsdlLocation(), EMPLOYEEPROFILEENDPOINTSERVICE_QNAME);
    }

    public EmployeeProfileEndpointService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPLOYEEPROFILEENDPOINTSERVICE_QNAME, features);
    }

    public EmployeeProfileEndpointService(URL wsdlLocation) {
        super(wsdlLocation, EMPLOYEEPROFILEENDPOINTSERVICE_QNAME);
    }

    public EmployeeProfileEndpointService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPLOYEEPROFILEENDPOINTSERVICE_QNAME, features);
    }

    public EmployeeProfileEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeeProfileEndpointService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmployeeProfileEndpoint
     */
    @WebEndpoint(name = "EmployeeProfileEndpointPort")
    public EmployeeProfileEndpoint getEmployeeProfileEndpointPort() {
        return super.getPort(new QName("http://endpoint.webservice.employee.app/", "EmployeeProfileEndpointPort"), EmployeeProfileEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmployeeProfileEndpoint
     */
    @WebEndpoint(name = "EmployeeProfileEndpointPort")
    public EmployeeProfileEndpoint getEmployeeProfileEndpointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://endpoint.webservice.employee.app/", "EmployeeProfileEndpointPort"), EmployeeProfileEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPLOYEEPROFILEENDPOINTSERVICE_EXCEPTION!= null) {
            throw EMPLOYEEPROFILEENDPOINTSERVICE_EXCEPTION;
        }
        return EMPLOYEEPROFILEENDPOINTSERVICE_WSDL_LOCATION;
    }

}
