
package app.employee.webservice.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeProfileEndpoint", targetNamespace = "http://endpoint.webservice.employee.app/")
@XmlSeeAlso({
    app.employee.webservice.endpoint.ObjectFactory.class,
    services.employee.ObjectFactory.class
})
public interface EmployeeProfileEndpoint {


    /**
     * 
     * @param arg0
     * @return
     *     returns app.employee.webservice.endpoint.ListFilteredEmployeeResponse.Return
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listFilteredEmployee", targetNamespace = "http://endpoint.webservice.employee.app/", className = "app.employee.webservice.endpoint.ListFilteredEmployee")
    @ResponseWrapper(localName = "listFilteredEmployeeResponse", targetNamespace = "http://endpoint.webservice.employee.app/", className = "app.employee.webservice.endpoint.ListFilteredEmployeeResponse")
    @Action(input = "http://endpoint.webservice.employee.app/EmployeeProfileEndpoint/listFilteredEmployeeRequest", output = "http://endpoint.webservice.employee.app/EmployeeProfileEndpoint/listFilteredEmployeeResponse")
    public app.employee.webservice.endpoint.ListFilteredEmployeeResponse.Return listFilteredEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        app.employee.webservice.endpoint.ListFilteredEmployee.Arg0 arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns app.employee.webservice.endpoint.AddNewEmployeeAddressResponse.Return
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addNewEmployeeAddress", targetNamespace = "http://endpoint.webservice.employee.app/", className = "app.employee.webservice.endpoint.AddNewEmployeeAddress")
    @ResponseWrapper(localName = "addNewEmployeeAddressResponse", targetNamespace = "http://endpoint.webservice.employee.app/", className = "app.employee.webservice.endpoint.AddNewEmployeeAddressResponse")
    @Action(input = "http://endpoint.webservice.employee.app/EmployeeProfileEndpoint/addNewEmployeeAddressRequest", output = "http://endpoint.webservice.employee.app/EmployeeProfileEndpoint/addNewEmployeeAddressResponse")
    public app.employee.webservice.endpoint.AddNewEmployeeAddressResponse.Return addNewEmployeeAddress(
        @WebParam(name = "arg0", targetNamespace = "")
        app.employee.webservice.endpoint.AddNewEmployeeAddress.Arg0 arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns app.employee.webservice.endpoint.AddNewEmployeeResponse.Return
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addNewEmployee", targetNamespace = "http://endpoint.webservice.employee.app/", className = "app.employee.webservice.endpoint.AddNewEmployee")
    @ResponseWrapper(localName = "addNewEmployeeResponse", targetNamespace = "http://endpoint.webservice.employee.app/", className = "app.employee.webservice.endpoint.AddNewEmployeeResponse")
    @Action(input = "http://endpoint.webservice.employee.app/EmployeeProfileEndpoint/addNewEmployeeRequest", output = "http://endpoint.webservice.employee.app/EmployeeProfileEndpoint/addNewEmployeeResponse")
    public app.employee.webservice.endpoint.AddNewEmployeeResponse.Return addNewEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        app.employee.webservice.endpoint.AddNewEmployee.Arg0 arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns app.employee.webservice.endpoint.ListEmployeeResponse.Return
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listEmployee", targetNamespace = "http://endpoint.webservice.employee.app/", className = "app.employee.webservice.endpoint.ListEmployee")
    @ResponseWrapper(localName = "listEmployeeResponse", targetNamespace = "http://endpoint.webservice.employee.app/", className = "app.employee.webservice.endpoint.ListEmployeeResponse")
    @Action(input = "http://endpoint.webservice.employee.app/EmployeeProfileEndpoint/listEmployeeRequest", output = "http://endpoint.webservice.employee.app/EmployeeProfileEndpoint/listEmployeeResponse")
    public app.employee.webservice.endpoint.ListEmployeeResponse.Return listEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        app.employee.webservice.endpoint.ListEmployee.Arg0 arg0);

}
