
package web;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeSoap", targetNamespace = "http://web/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeSoap {


    /**
     * 
     * @return
     *     returns web.EmployeeCard
     */
    @WebMethod
    @WebResult(name = "EmployeeCards", partName = "EmployeeCards")
    @Action(input = "http://web/EmployeeSoap/readAllRequest", output = "http://web/EmployeeSoap/readAllResponse")
    public EmployeeCard readAll();

    /**
     * 
     * @param addEmployeeDetails
     */
    @WebMethod
    @Action(input = "http://web/EmployeeSoap/addEmployeeDetailsRequest", output = "http://web/EmployeeSoap/addEmployeeDetailsResponse")
    public void addEmployeeDetails(
        @WebParam(name = "addEmployeeDetails", partName = "addEmployeeDetails")
        EmployeeDetails addEmployeeDetails);

    /**
     * 
     * @param addEmployeePermanentAddress
     * @param addEmployeeTemporaryAddress
     */
    @WebMethod
    @Action(input = "http://web/EmployeeSoap/addEmployeeAddressRequest", output = "http://web/EmployeeSoap/addEmployeeAddressResponse")
    public void addEmployeeAddress(
        @WebParam(name = "addEmployeePermanentAddress", partName = "addEmployeePermanentAddress")
        EmployeeAddress addEmployeePermanentAddress,
        @WebParam(name = "addEmployeeTemporaryAddress", partName = "addEmployeeTemporaryAddress")
        EmployeeAddress addEmployeeTemporaryAddress);

    /**
     * 
     * @param integerPincode
     * @return
     *     returns web.EmployeeCard
     */
    @WebMethod
    @WebResult(name = "EmployeeCards", partName = "EmployeeCards")
    @Action(input = "http://web/EmployeeSoap/readByFilterPincodeRequest", output = "http://web/EmployeeSoap/readByFilterPincodeResponse")
    public EmployeeCard readByFilterPincode(
        @WebParam(name = "IntegerPincode", partName = "IntegerPincode")
        int integerPincode);

}
