
package web;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeSoap", targetNamespace = "http://web/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeSoap {


    /**
     * 
     * @return
     *     returns web.EmployeeCard
     * @throws SOAPException_Exception
     */
    @WebMethod
    @WebResult(name = "EmployeeCards", partName = "EmployeeCards")
    @Action(input = "http://web/EmployeeSoap/readAllRequest", output = "http://web/EmployeeSoap/readAllResponse", fault = {
        @FaultAction(className = SOAPException_Exception.class, value = "http://web/EmployeeSoap/readAll/Fault/SOAPException")
    })
    public EmployeeCard readAll()
        throws SOAPException_Exception
    ;

    /**
     * 
     * @param addEmployeeDetails
     * @throws SOAPException_Exception
     */
    @WebMethod
    @Action(input = "http://web/EmployeeSoap/addEmployeeDetailsRequest", output = "http://web/EmployeeSoap/addEmployeeDetailsResponse", fault = {
        @FaultAction(className = SOAPException_Exception.class, value = "http://web/EmployeeSoap/addEmployeeDetails/Fault/SOAPException")
    })
    public void addEmployeeDetails(
        @WebParam(name = "addEmployeeDetails", partName = "addEmployeeDetails")
        EmployeeDetails addEmployeeDetails)
        throws SOAPException_Exception
    ;

    /**
     * 
     * @param integerPincode
     * @return
     *     returns web.EmployeeCard
     * @throws SOAPException_Exception
     */
    @WebMethod
    @WebResult(name = "EmployeeCards", partName = "EmployeeCards")
    @Action(input = "http://web/EmployeeSoap/readByFilterPincodeRequest", output = "http://web/EmployeeSoap/readByFilterPincodeResponse", fault = {
        @FaultAction(className = SOAPException_Exception.class, value = "http://web/EmployeeSoap/readByFilterPincode/Fault/SOAPException")
    })
    public EmployeeCard readByFilterPincode(
        @WebParam(name = "IntegerPincode", partName = "IntegerPincode")
        int integerPincode)
        throws SOAPException_Exception
    ;

    /**
     * 
     * @param addEmployeePermanentAddress
     * @param addEmployeeTemporaryAddress
     * @throws SOAPException_Exception
     */
    @WebMethod
    @Action(input = "http://web/EmployeeSoap/addEmployeeAddressRequest", output = "http://web/EmployeeSoap/addEmployeeAddressResponse", fault = {
        @FaultAction(className = SOAPException_Exception.class, value = "http://web/EmployeeSoap/addEmployeeAddress/Fault/SOAPException")
    })
    public void addEmployeeAddress(
        @WebParam(name = "addEmployeePermanentAddress", partName = "addEmployeePermanentAddress")
        EmployeeAddress addEmployeePermanentAddress,
        @WebParam(name = "addEmployeeTemporaryAddress", partName = "addEmployeeTemporaryAddress")
        EmployeeAddress addEmployeeTemporaryAddress)
        throws SOAPException_Exception
    ;

}
