
package web;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TransactionsSoap", targetNamespace = "http://web/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TransactionsSoap {


    /**
     * 
     * @return
     *     returns web.GroupOfTransactions
     */
    @WebMethod
    @WebResult(name = "GroupOfTransactions", partName = "GroupOfTransactions")
    @Action(input = "http://web/TransactionsSoap/readAllRequest", output = "http://web/TransactionsSoap/readAllResponse")
    public GroupOfTransactions readAll();

}
