//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.18 at 10:14:05 PM IST 
//


package services.employee;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the services.employee package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: services.employee
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CallFilterEmployeeRequest }
     * 
     */
    public CallFilterEmployeeRequest createCallFilterEmployeeRequest() {
        return new CallFilterEmployeeRequest();
    }

    /**
     * Create an instance of {@link CallInsertEmployeeDetailsRequest }
     * 
     */
    public CallInsertEmployeeDetailsRequest createCallInsertEmployeeDetailsRequest() {
        return new CallInsertEmployeeDetailsRequest();
    }

    /**
     * Create an instance of {@link EmployeeDetails }
     * 
     */
    public EmployeeDetails createEmployeeDetails() {
        return new EmployeeDetails();
    }

    /**
     * Create an instance of {@link CallOutputEmployeeResponse }
     * 
     */
    public CallOutputEmployeeResponse createCallOutputEmployeeResponse() {
        return new CallOutputEmployeeResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link CallFilterEmployeeResponse }
     * 
     */
    public CallFilterEmployeeResponse createCallFilterEmployeeResponse() {
        return new CallFilterEmployeeResponse();
    }

    /**
     * Create an instance of {@link CallOutputEmployeeRequest }
     * 
     */
    public CallOutputEmployeeRequest createCallOutputEmployeeRequest() {
        return new CallOutputEmployeeRequest();
    }

    /**
     * Create an instance of {@link CallInsertEmployeeDetailsResponse }
     * 
     */
    public CallInsertEmployeeDetailsResponse createCallInsertEmployeeDetailsResponse() {
        return new CallInsertEmployeeDetailsResponse();
    }

    /**
     * Create an instance of {@link EmployeeHttpResponse }
     * 
     */
    public EmployeeHttpResponse createEmployeeHttpResponse() {
        return new EmployeeHttpResponse();
    }

    /**
     * Create an instance of {@link EmployeeAddress }
     * 
     */
    public EmployeeAddress createEmployeeAddress() {
        return new EmployeeAddress();
    }

}
