//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.07 at 11:54:57 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://insurance.services", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package services.insurance;
